[workspace]
authors = ["Konstantin Makarchev <kostya27@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
mojo = "=1.0.0"
csv = { git = "https://github.com/millfolio/csv.mojo.git", rev = "667a23f91b22546e2320082a59af07ecba56b6fa" }
max = ">0" 
